--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Tue Jan 30 2018
--=======================================================================================
modifier_panic = modifier_panic or {}
modifier_panic.__index = modifier_panic
function modifier_panic.new(construct, ...)
    local instance = setmetatable({}, modifier_panic)
    if construct and modifier_panic.constructor then modifier_panic.constructor(instance, ...) end
    return instance
end
function modifier_panic.CheckState(self)
    return {[MODIFIER_STATE_COMMAND_RESTRICTED]=true}
end
function modifier_panic.DeclareFunctions(self)
    return {MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE}
end
function modifier_panic.GetModifierMoveSpeed_Absolute(self)
    return 540
end
function modifier_panic.OnCreated(self,params)
    self.StartIntervalThink(self,0.3)
end
function modifier_panic.OnIntervalThink(self)
    local parent = self.GetParent(self)
    if parent.GetAbsOrigin(parent).Length2D(parent.GetAbsOrigin(parent))<500 then
        parent.MoveToPosition(parent,parent.GetAbsOrigin(parent)+RandomVector(400))
    else
        parent.MoveToPosition(parent,RandomVector(300))
    end
end
