--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Wed Jan 31 2018
--=======================================================================================
require("lib.typescript")
LinkLuaModifier("modifier_panic","modifiers/modifier_panic.lua",LUA_MODIFIER_MOTION_NONE)
function Precache(context)
end
function Activate()
    local mode = GameRules.GetGameModeEntity(GameRules)
    mode.SetFogOfWarDisabled(mode,true)
    mode.SetCustomGameForceHero(mode,"npc_dota_hero_jakiro")
    mode.SetWeatherEffectsDisabled(mode,true)
    mode.SetCustomAttributeDerivedStatValue(mode,DOTA_ATTRIBUTE_AGILITY_ARMOR,0)
    GameRules.SetHeroRespawnEnabled(GameRules,false)
    ListenToGameEvent("game_rules_state_change",OnStateChange,nil)
end
function OnStateChange()
    local state = GameRules.State_Get(GameRules)
    if state==DOTA_GAMERULES_STATE_PRE_GAME then
        StartGame()
    end
end
function StartGame()
    local players = {}
    for pID=0,DOTA_MAX_TEAM_PLAYERS-1,1 do
        if PlayerResource.IsValidPlayer(PlayerResource,pID) then
            table.insert(players, pID)
        end
    end
    local myGameMode = MyGameMode.new(true,players)
    myGameMode.Init(myGameMode)
end
MyGameMode = MyGameMode or {}
MyGameMode.__index = MyGameMode
function MyGameMode.new(construct, ...)
    local instance = setmetatable({}, MyGameMode)
    if construct and MyGameMode.constructor then MyGameMode.constructor(instance, ...) end
    return instance
end
function MyGameMode.constructor(self,players)
    self.players=players
end
function MyGameMode.Init(self)
    print("Starting game with "..#self.players.." players!")
    ListenToGameEvent("npc_spawned",function(event) return self.OnNpcSpawn(self,event) end,nil)
    GameRules.GetGameModeEntity(GameRules).SetExecuteOrderFilter(GameRules.GetGameModeEntity(GameRules),function(ctx,order) return self.OnExecuteOrder(self,order) end,self)
end
function MyGameMode.OnNpcSpawn(self,event)
    local unit = EntIndexToHScript(event.entindex)
    unit.AddNewModifier(unit,nil,nil,"modifier_panic",{duration=8})
end
function MyGameMode.OnExecuteOrder(self,order)
    print(order.order_type)
    return true
end
