name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.X
        
    - name: npm install, build, and test
      working-directory: ./override_validate
      run: |
        yarn
        yarn test
      env:
        CI: true
